version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant_financial_rag
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - rag_network

  # Uncomment if you want to run Ollama in Docker as well
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama_financial_rag
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_ORIGINS=*
  #   restart: unless-stopped
  #   networks:
  #     - rag_network

volumes:
  qdrant_storage:
  # ollama_data:

networks:
  rag_network:
    driver: bridge